syncing with upstream, rebased all existing patches againt current version. _only_ splashy integration seems busted atm.

diff --git a/mkinitrd/mkinitrd-6.0.87-usbstorage.patch b/mkinitrd/mkinitrd-6.0.87-usbstorage.patch
--- a/mkinitrd/mkinitrd-6.0.87-usbstorage.patch
+++ b/mkinitrd/mkinitrd-6.0.87-usbstorage.patch
@@ -1,16 +1,17 @@
---- mkinitrd	2009-03-16 18:41:42.000000000 -0400
-+++ mkinitrd	2009-03-16 18:45:21.000000000 -0400
-@@ -287,6 +287,7 @@
- 
+diff -u --recursive mkinitrd-6.0.87.orig/mkinitrd mkinitrd-6.0.87/mkinitrd
+--- mkinitrd-6.0.87.orig/mkinitrd	2009-08-25 12:24:40.205391000 +0100
++++ mkinitrd-6.0.87/mkinitrd	2009-08-25 12:26:51.426012988 +0100
+@@ -68,6 +68,7 @@
+ root=""
  stabalize_scsi="no"
  scsi_wait_scan="no"
 +usb_storage="no"
- findmodule() {
-     skiperrors=""
  
-@@ -385,6 +386,16 @@
-     # only need to add each module once
-     [[ "$MODULES" =~ $modName ]] || MODULES="$MODULES $modName"
+ NET_LIST=""
+ LD_SO_CONF=/etc/ld.so.conf
+@@ -263,6 +264,16 @@
+         FIRMWARE=" $(cat /etc/mkinitrd-firmware.d/$modName)"
+     fi
  
 +    # add usb storage module if we're including usb support
 +    if [    "$modName" = "uhci-hcd" \
@@ -25,7 +26,7 @@
      # need to handle prescsimods here -- they need to go _after_ scsi_mod
      if [ "$modName" = "scsi_mod" ]; then
          for n in $PRESCSIMODS ; do
-@@ -1715,6 +1726,11 @@
+@@ -1590,6 +1601,11 @@
      installmodule scsi_wait_scan
  fi
  
@@ -34,6 +35,6 @@
 +    installmodule usb-storage
 +fi
 +
- /sbin/depmod -F /boot/System.map-$kernel -a -b $MNTIMAGE $kernel
- 
- usb_mounted="prep"
+ /sbin/depmod -a -b $MNTIMAGE $kernel
+ if [ $? -ne 0 ]; then
+     error "\"/sbin/depmod -a $kernel\" failed."
