automated promote

diff --git a/mkinitrd/mkinitrd-6.0.45-usbstorage.patch b/mkinitrd/mkinitrd-6.0.45-usbstorage.patch
--- a/mkinitrd/mkinitrd-6.0.45-usbstorage.patch
+++ b/mkinitrd/mkinitrd-6.0.45-usbstorage.patch
@@ -1,13 +1,13 @@
 --- mkinitrd	2009-03-16 18:41:42.000000000 -0400
 +++ mkinitrd	2009-03-16 18:45:21.000000000 -0400
-@@ -287,6 +287,7 @@
- 
- stabalize_scsi="no"
+@@ -67,6 +67,7 @@
+ ncryptoraids=0
+ root=""
  scsi_wait_scan="no"
 +usb_storage="no"
- findmodule() {
-     skiperrors=""
  
+ NET_LIST=""
+ LD_SO_CONF=/etc/ld.so.conf
 @@ -385,6 +386,16 @@
      # only need to add each module once
      [[ "$MODULES" =~ $modName ]] || MODULES="$MODULES $modName"
@@ -25,7 +25,7 @@
      # need to handle prescsimods here -- they need to go _after_ scsi_mod
      if [ "$modName" = "scsi_mod" ]; then
          for n in $PRESCSIMODS ; do
-@@ -1715,6 +1726,11 @@
+@@ -1717,6 +1717,11 @@
      installmodule scsi_wait_scan
  fi
  
@@ -34,6 +34,6 @@
 +    installmodule usb-storage
 +fi
 +
- /sbin/depmod -F /boot/System.map-$kernel -a -b $MNTIMAGE $kernel
- 
- usb_mounted="prep"
+ /sbin/depmod -a -b $MNTIMAGE $kernel
+ if [ $? -ne 0 ]; then
+     error "\"/sbin/depmod -a $kernel\" failed."
