New version

diff --git a/gnome-volume-manager/99_autotools.patch b/gnome-volume-manager/99_autotools.patch
--- a/gnome-volume-manager/99_autotools.patch
+++ b/gnome-volume-manager/99_autotools.patch
@@ -1,7 +1,7 @@
-diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/configure
---- gnome-volume-manager-1.3.1-old/configure	2005-03-31 18:28:08.000000000 +0200
-+++ gnome-volume-manager-1.3.1/configure	2005-06-22 14:23:42.000000000 +0200
-@@ -957,7 +957,7 @@
+diff -ruN gnome-volume-manager-1.3.2-old/configure gnome-volume-manager-1.3.2/configure
+--- gnome-volume-manager-1.3.2-old/configure	2005-07-01 16:58:16.000000000 +0200
++++ gnome-volume-manager-1.3.2/configure	2005-07-04 17:34:18.500079808 +0200
+@@ -988,7 +988,7 @@
      else
        echo "$as_me: WARNING: no configuration information is in $ac_dir" >&2
      fi
@@ -10,7 +10,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    done
  fi
  
-@@ -2272,8 +2272,7 @@
+@@ -2354,8 +2354,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -20,7 +20,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -2331,8 +2330,7 @@
+@@ -2413,8 +2412,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -30,7 +30,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -2448,8 +2446,7 @@
+@@ -2530,8 +2528,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -40,7 +40,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -2503,8 +2500,7 @@
+@@ -2585,8 +2582,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -50,7 +50,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -2549,8 +2545,7 @@
+@@ -2631,8 +2627,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -60,7 +60,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -2594,8 +2589,7 @@
+@@ -2676,8 +2671,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -70,7 +70,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -3595,8 +3589,7 @@
+@@ -3739,8 +3733,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -80,7 +80,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -3766,8 +3759,7 @@
+@@ -3910,8 +3903,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -90,7 +90,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -3835,8 +3827,7 @@
+@@ -3979,8 +3971,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -100,7 +100,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -3981,8 +3972,7 @@
+@@ -4125,8 +4116,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -110,7 +110,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -4053,8 +4043,7 @@
+@@ -4197,8 +4187,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -120,7 +120,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -4198,8 +4187,7 @@
+@@ -4342,8 +4331,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -130,7 +130,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -4257,8 +4245,7 @@
+@@ -4401,8 +4389,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -140,7 +140,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -4355,8 +4342,7 @@
+@@ -4499,8 +4486,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -150,7 +150,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -4435,8 +4421,7 @@
+@@ -4579,8 +4565,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -160,7 +160,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -4500,8 +4485,7 @@
+@@ -4644,8 +4629,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -170,7 +170,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -4565,8 +4549,7 @@
+@@ -4709,8 +4693,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -180,7 +180,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -4643,8 +4626,7 @@
+@@ -4787,8 +4770,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -190,7 +190,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -4708,8 +4690,7 @@
+@@ -4852,8 +4834,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -200,7 +200,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -4825,8 +4806,7 @@
+@@ -4969,8 +4950,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -210,7 +210,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -4993,8 +4973,7 @@
+@@ -5137,8 +5117,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -220,7 +220,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -5127,8 +5106,7 @@
+@@ -5271,8 +5250,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -230,7 +230,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -5213,8 +5191,7 @@
+@@ -5357,8 +5335,7 @@
    cat conftest.err >&5
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } &&
@@ -240,56 +240,61 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
    (eval $ac_try) 2>&5
    ac_status=$?
-@@ -5423,23 +5400,23 @@
-   else
-      PKG_CONFIG_MIN_VERSION=0.9.0
-      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
--        echo "$as_me:$LINENO: checking for libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0" >&5
--echo $ECHO_N "checking for libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0... $ECHO_C" >&6
-+        echo "$as_me:$LINENO: checking for libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0 libgksuui1.0 >= 1.0.0" >&5
-+echo $ECHO_N "checking for libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0 libgksuui1.0 >= 1.0.0... $ECHO_C" >&6
+@@ -5619,12 +5596,12 @@
+   if test "x$ac_cv_env_GVM_CFLAGS_set" = "xset"; then
+ 	pkg_cv_GVM_CFLAGS=$ac_cv_env_GVM_CFLAGS_value
+ elif test -n "$PKG_CONFIG"; then
+-	if { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists \"libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0\" >/dev/null 2>&1") >&5
+-  ($PKG_CONFIG --exists "libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0" >/dev/null 2>&1) 2>&5
++	if { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists \"libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0 libgksuui1.0 >= 1.0.0\" >/dev/null 2>&1") >&5
++  ($PKG_CONFIG --exists "libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0 libgksuui1.0 >= 1.0.0" >/dev/null 2>&1) 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-		pkg_cv_GVM_CFLAGS=`$PKG_CONFIG --cflags "libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0" 2>/dev/null`
++		pkg_cv_GVM_CFLAGS=`$PKG_CONFIG --cflags "libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0 libgksuui1.0 >= 1.0.0" 2>/dev/null`
+ 	else
+ 		pkg_failed=yes
+ 	fi
+@@ -5642,12 +5619,12 @@
+   if test "x$ac_cv_env_GVM_LIBS_set" = "xset"; then
+ 	pkg_cv_GVM_LIBS=$ac_cv_env_GVM_LIBS_value
+ elif test -n "$PKG_CONFIG"; then
+-	if { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists \"libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0\" >/dev/null 2>&1") >&5
+-  ($PKG_CONFIG --exists "libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0" >/dev/null 2>&1) 2>&5
++	if { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists \"libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0 libgksuui1.0 >= 1.0.0\" >/dev/null 2>&1") >&5
++  ($PKG_CONFIG --exists "libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0 libgksuui1.0 >= 1.0.0" >/dev/null 2>&1) 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-		pkg_cv_GVM_LIBS=`$PKG_CONFIG --libs "libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0" 2>/dev/null`
++		pkg_cv_GVM_LIBS=`$PKG_CONFIG --libs "libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0 libgksuui1.0 >= 1.0.0" 2>/dev/null`
+ 	else
+ 		pkg_failed=yes
+ 	fi
+@@ -5659,18 +5636,18 @@
+ echo "${ECHO_T}$pkg_cv_GVM_LIBS" >&6
  
--        if $PKG_CONFIG --exists "libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0" ; then
-+        if $PKG_CONFIG --exists "libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0 libgksuui1.0 >= 1.0.0" ; then
-             echo "$as_me:$LINENO: result: yes" >&5
- echo "${ECHO_T}yes" >&6
-             succeeded=yes
+ if test $pkg_failed = yes; then
+-	GVM_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0"`
++	GVM_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0 libgksuui1.0 >= 1.0.0"`
+ 	# Put the nasty error message in config.log where it belongs
+ 	echo "$GVM_PKG_ERRORS" 1>&5
  
-             echo "$as_me:$LINENO: checking GVM_CFLAGS" >&5
- echo $ECHO_N "checking GVM_CFLAGS... $ECHO_C" >&6
--            GVM_CFLAGS=`$PKG_CONFIG --cflags "libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0"`
-+            GVM_CFLAGS=`$PKG_CONFIG --cflags "libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0 libgksuui1.0 >= 1.0.0"`
-             echo "$as_me:$LINENO: result: $GVM_CFLAGS" >&5
- echo "${ECHO_T}$GVM_CFLAGS" >&6
+-	{ { echo "$as_me:$LINENO: error: Package requirements (libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0) were not met.
++	{ { echo "$as_me:$LINENO: error: Package requirements (libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0 libgksuui1.0 >= 1.0.0) were not met.
+ Consider adjusting the PKG_CONFIG_PATH environment variable if you
+ installed software in a non-standard prefix.
  
-             echo "$as_me:$LINENO: checking GVM_LIBS" >&5
- echo $ECHO_N "checking GVM_LIBS... $ECHO_C" >&6
--            GVM_LIBS=`$PKG_CONFIG --libs "libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0"`
-+            GVM_LIBS=`$PKG_CONFIG --libs "libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0 libgksuui1.0 >= 1.0.0"`
-             echo "$as_me:$LINENO: result: $GVM_LIBS" >&5
- echo "${ECHO_T}$GVM_LIBS" >&6
-         else
-@@ -5447,7 +5424,7 @@
-             GVM_LIBS=""
-             ## If we have a custom action on failure, don't print errors, but
-             ## do set a variable so people can do so.
--            GVM_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0"`
-+            GVM_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0 libgksuui1.0 >= 1.0.0"`
-             echo $GVM_PKG_ERRORS
-         fi
+ Alternatively you may set the GVM_CFLAGS and GVM_LIBS environment variables
+ to avoid the need to call pkg-config.  See the pkg-config man page for
+ more details." >&5
+-echo "$as_me: error: Package requirements (libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0) were not met.
++echo "$as_me: error: Package requirements (libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0 libgksuui1.0 >= 1.0.0) were not met.
+ Consider adjusting the PKG_CONFIG_PATH environment variable if you
+ installed software in a non-standard prefix.
  
-@@ -5462,8 +5439,8 @@
-   if test $succeeded = yes; then
-      :
-   else
--     { { echo "$as_me:$LINENO: error: Library requirements (libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
--echo "$as_me: error: Library requirements (libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
-+     { { echo "$as_me:$LINENO: error: Library requirements (libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0 libgksuui1.0 >= 1.0.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-+echo "$as_me: error: Library requirements (libgnomeui-2.0 dbus-glib-1 >= 0.31 hal >= 0.5.0 gtk+-2.0 >= 2.6.0 libgksuui1.0 >= 1.0.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
-    { (exit 1); exit 1; }; }
-   fi
- 
-@@ -6580,11 +6557,6 @@
+@@ -6829,11 +6806,6 @@
    *) ac_INSTALL=$ac_top_builddir$INSTALL ;;
    esac
  
@@ -301,7 +306,7 @@ diff -ruN gnome-volume-manager-1.3.1-old/configure gnome-volume-manager-1.3.1/co
    # Let's still pretend it is `configure' which instantiates (i.e., don't
    # use $as_me), people would be surprised to read:
    #    /* config.h.  Generated by config.status.  */
-@@ -6623,6 +6595,12 @@
+@@ -6872,6 +6844,12 @@
  	 fi;;
        esac
      done` || { (exit 1); exit 1; }
